
export const CHANGE_LAYOUT = "CHANGE_LAYOUT";
export const TOGGLE_LEFTMENU = "TOGGLE_LEFTMENU";
export const CHANGE_SIDEBAR_TYPE = "CHANGE_SIDEBAR_TYPE"
export const CHANGE_LAYOUT_WIDTH = "CHANGE_LAYOUT_WIDTH"
export const SHOW_SIDEBAR = "SHOW_SIDEBAR"
export const CHANGE_SIDEBAT_THEME = "CHANGE_SIDEBAT_THEME"
export const SHOW_RIGHT_SIDEBAR = "SHOW_RIGHT_SIDEBAR"
export const CHANGE_TOPBAR_THEME = "CHANGE_TOPBAR_THEME"
export const CHANGE_PRELOADER = "CHANGE_PRELOADER"
export const CHANGE_THEME = "CHANGE_THEME"